const language = {
    en: {
      title: "My contribution to AI",
      data: [
        "At Scale AI as part of the Generative AI team, I analyzed code samples written in Java, JavaScript, TypeScript and Python, which were generated by a Large Language Model. These code samples included web applications, AI implementations, data structures and algorithms.",
        "I worked quantifying and ranking responses generated by the LLM in terms of quality, precision, and structure.",
        "I also worked writing and editing code written by the LLM with reasoning to fix bugs and improve performance."
      ],
    },
    es: {
      title: "Mi contribución a la IA",
      data: [
        "En Scale AI como parte del equipo de desarrollo de IA, analicé ejemplos de código escritos en Java, JavaScript, TypeScript y Python, los cuales eran generados por un LLM. Estos ejemplos de código incluían aplicaciones web, implementaciones de IA, estructuras de datos y algoritmos, entre otros ejemplos.",
        "Trabaje cuantificando y clasificando las respuestas generadas por el LLM en términos de calidad, precisión y estructura tanto del código como de la explicación",
        "También trabajé escribiendo y editando el código escrito por el LLM con razonamiento para corregir errores y mejorar el rendimiento, seguir mejores practicas, y documentarlos."
      ],
    },
  };
  
  export default language;
  